import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const leads = sqliteTable(
  "leads",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    organization: text("organization").notNull(),
    interest: text("interest").notNull(),
    message: text("message").notNull(),
    status: text("status").notNull().default("new"),
    notes: text("notes").notNull().default(""),
    owner: text("owner").notNull().default(""),
    sourcePage: text("source_page").notNull().default("/"),
    referrer: text("referrer").notNull().default(""),
    utmSource: text("utm_source").notNull().default(""),
    utmMedium: text("utm_medium").notNull().default(""),
    utmCampaign: text("utm_campaign").notNull().default(""),
    utmContent: text("utm_content").notNull().default(""),
    utmTerm: text("utm_term").notNull().default(""),
    sessionId: text("session_id").notNull().default(""),
    country: text("country").notNull().default(""),
    region: text("region").notNull().default(""),
    city: text("city").notNull().default(""),
    timezone: text("timezone").notNull().default(""),
    ipAddress: text("ip_address").notNull().default(""),
    ipHash: text("ip_hash").notNull().default(""),
    ipMasked: text("ip_masked").notNull().default(""),
    userAgent: text("user_agent").notNull().default(""),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [
    index("leads_created_at_idx").on(table.createdAt),
    index("leads_status_idx").on(table.status),
    index("leads_email_idx").on(table.email),
    index("leads_session_idx").on(table.sessionId),
  ],
);

export const events = sqliteTable(
  "events",
  {
    id: text("id").primaryKey(),
    sessionId: text("session_id").notNull(),
    eventType: text("event_type").notNull(),
    path: text("path").notNull().default("/"),
    target: text("target").notNull().default(""),
    label: text("label").notNull().default(""),
    referrer: text("referrer").notNull().default(""),
    utmSource: text("utm_source").notNull().default(""),
    utmMedium: text("utm_medium").notNull().default(""),
    utmCampaign: text("utm_campaign").notNull().default(""),
    utmContent: text("utm_content").notNull().default(""),
    utmTerm: text("utm_term").notNull().default(""),
    country: text("country").notNull().default(""),
    region: text("region").notNull().default(""),
    city: text("city").notNull().default(""),
    timezone: text("timezone").notNull().default(""),
    deviceType: text("device_type").notNull().default("unknown"),
    browser: text("browser").notNull().default("unknown"),
    ipAddress: text("ip_address").notNull().default(""),
    ipHash: text("ip_hash").notNull().default(""),
    ipMasked: text("ip_masked").notNull().default(""),
    createdAt: integer("created_at").notNull(),
  },
  (table) => [
    index("events_created_at_idx").on(table.createdAt),
    index("events_session_idx").on(table.sessionId),
    index("events_type_idx").on(table.eventType),
    index("events_country_idx").on(table.country),
  ],
);

export const adminAudit = sqliteTable(
  "admin_audit",
  {
    id: text("id").primaryKey(),
    adminEmail: text("admin_email").notNull(),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    details: text("details").notNull().default(""),
    createdAt: integer("created_at").notNull(),
  },
  (table) => [index("admin_audit_created_at_idx").on(table.createdAt)],
);
